project_name: go-cipherguard-cli
checksum:
  name_template: 'checksums.txt'
builds:
  - env: [CGO_ENABLED=0]
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: cipherguard
archives:
  - files:
      - completion/*
      - man/*
    format_overrides:
      - goos: windows
        format: zip
release:
  draft: true
  header: |
    ## Release {{ .Tag }} - ({{ .Date }})
nfpms:
- maintainer: Samuel Lorch <sam@soontm.de>
  description: A CLI for Cipherguard.
  homepage: https://github.com/khulnasoft/go-cipherguard-cli
  license: MIT
  contents:
    - src: /home/runner/work/go-cipherguard-cli/go-cipherguard-cli/completion/bash
      dst: /usr/share/bash-completion/completions/cipherguard
    - src: /home/runner/work/go-cipherguard-cli/go-cipherguard-cli/completion/zsh
      dst: /usr/share/zsh/site-functions/_cipherguard
    - src: /home/runner/work/go-cipherguard-cli/go-cipherguard-cli/completion/fish
      dst: /usr/share/fish/vendor_completions.d/cipherguard.fish
    - src: /home/runner/work/go-cipherguard-cli/go-cipherguard-cli/man/*
      dst: /usr/share/man/man1/
  recommends:
    - bash_completion
  formats:
    - deb
    - rpm
brews:
  - homepage: https://github.com/khulnasoft/go-cipherguard-cli
    license: "MIT"
    skip_upload: false
    description: "A CLI tool to interact with Cipherguard, a Open source Password Manager for Teams"
    directory: Formula
    install: |
      bin.install "cipherguard"
      bash_completion.install "completion/bash" => "cipherguard"
      zsh_completion.install "completion/zsh" => "_cipherguard"
      fish_completion.install "completion/fish" => "cipherguard.fish"
      man1.install Dir["man/*"]
      # ...
    repository:
      owner: khulnasoft
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
        

