name: Go

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -o cipherguard

    - name: Update Wiki
      run: |
        mkdir doc
        ls
        ./cipherguard gendoc
      
    - name: Upload Documentation to Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
       path: "doc"
      env:
       GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
