name: goreleaser

on:
  push:
    tag: '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - 
        name: Generate Man and Completions
        run: |
          mkdir completion
          go run main.go completion bash > completion/bash
          go run main.go completion zsh > completion/zsh
          go run main.go completion fish > completion/fish
          go run main.go completion powershell > completion/powershell
          mkdir man
          go run main.go gendoc --type man
          pwd
          ls
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
